name: CI
on: [push]

jobs:
  build-library:
    runs-on: ubuntu-latest
    name: build-library
    steps:
      - uses: actions/checkout@v1
      - uses: teddywilson/shisito-markdown-validation@v1.1.2
